export default {
  title: "Daniela Mulle — Diätologin & Ernährungswissenschafterin",
  author: "Daniela Mulle",
  authorDegree: "Mag.",
  email: "contact@danielamulle.at",
  phone: "+43 650 9700569",
  role: "Diätologin & Ernährungswissenschafterin",
  description: "Ernährungswissenschafterin & Diätologin aus Leidenschaft",
  homepage: "https://danielamulle.at",
  lang: "de",
  locale: "de_AT",
  socialHandle: "bauchdetektivin",
  collections: {
    about: "about",
    offers: "offers",
    recipes: "recipes",
    blog: "posts",
    projects: "projects",
    resources: "resources",
    legal: "legal",
  },
}
